algoritmo "Print salteando linha junto com variáveis" 

var x: caractere // Definição da Variável x e o Seu tipo

inicio // Define a Função Inicio   

    x <- "teste" // ATribuiu a variável x o texto "teste"

    escreval("Olá Mundo!")
    escreval(x, "ok")           // Escreve: teste ok (e depois pula linha)
    escreval(x, " ok")          // Escreve: teste  ok (e depois pula linha)
    escreva(x + " ok")          // Escreve: teste ok (e depois pula linha)

fimalgoritmo